<?php
require_once( 'dbconnect.php');
$a = $_GET['id'];
$result = mysql_query("select * from enrolled_details where id_no='$a'")
        or die(mysql_error());
if ($row = mysql_fetch_array($result)) {
    $b = $row['course_id'] ;

    //echo "<div>Selected Course -> $b ($a) </div>";
}
?>
<div id="menulist">
   <a href="stuindex.php?page=stuhome"> Back to home </a>
</div>

<br><br>
<br><a href="stuindex.php?page=class_attend&id=<?php echo $_GET["id"]; ?>"> Show Class Attendace </a>
